//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Запись IP адреса
 *             
 * 
 * <p>Java class for AddressIPRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressIPRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ipaId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="adressIPValue" type="{http://www.bercut.com/schema/commonInVoiceAPI}addressIP" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressIPRecord", propOrder = {
    "ipaId",
    "adressIPValue"
})
public class AddressIPRecord {

    protected BigDecimal ipaId;
    protected String adressIPValue;

    /**
     * Gets the value of the ipaId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIpaId() {
        return ipaId;
    }

    /**
     * Sets the value of the ipaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIpaId(BigDecimal value) {
        this.ipaId = value;
    }

    /**
     * Gets the value of the adressIPValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdressIPValue() {
        return adressIPValue;
    }

    /**
     * Sets the value of the adressIPValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdressIPValue(String value) {
        this.adressIPValue = value;
    }

}
