//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Набор информационных параметров скидки
 * 
 * <p>Java class for DiscountInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscountInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="discountId" type="{http://www.bercut.com/schema/commonInVoiceAPI}discountId" minOccurs="0"/&gt;
 *         &lt;element name="intDictId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="renewQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="sppmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="toNextPeriod" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="distId" type="{http://www.bercut.com/schema/commonInVoiceAPI}distId" minOccurs="0"/&gt;
 *         &lt;element name="tduId" type="{http://www.bercut.com/schema/commonInVoiceAPI}distId" minOccurs="0"/&gt;
 *         &lt;element name="dtrftId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscountInfo", propOrder = {
    "discountId",
    "intDictId",
    "renewQuantity",
    "sppmId",
    "toNextPeriod",
    "distId",
    "tduId",
    "dtrftId"
})
public class DiscountInfo {

    protected BigDecimal discountId;
    protected BigDecimal intDictId;
    protected BigDecimal renewQuantity;
    protected BigDecimal sppmId;
    protected BigDecimal toNextPeriod;
    protected BigDecimal distId;
    protected BigDecimal tduId;
    protected BigDecimal dtrftId;

    /**
     * Gets the value of the discountId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountId() {
        return discountId;
    }

    /**
     * Sets the value of the discountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountId(BigDecimal value) {
        this.discountId = value;
    }

    /**
     * Gets the value of the intDictId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntDictId() {
        return intDictId;
    }

    /**
     * Sets the value of the intDictId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntDictId(BigDecimal value) {
        this.intDictId = value;
    }

    /**
     * Gets the value of the renewQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRenewQuantity() {
        return renewQuantity;
    }

    /**
     * Sets the value of the renewQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRenewQuantity(BigDecimal value) {
        this.renewQuantity = value;
    }

    /**
     * Gets the value of the sppmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSppmId() {
        return sppmId;
    }

    /**
     * Sets the value of the sppmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSppmId(BigDecimal value) {
        this.sppmId = value;
    }

    /**
     * Gets the value of the toNextPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToNextPeriod() {
        return toNextPeriod;
    }

    /**
     * Sets the value of the toNextPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToNextPeriod(BigDecimal value) {
        this.toNextPeriod = value;
    }

    /**
     * Gets the value of the distId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistId() {
        return distId;
    }

    /**
     * Sets the value of the distId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistId(BigDecimal value) {
        this.distId = value;
    }

    /**
     * Gets the value of the tduId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTduId() {
        return tduId;
    }

    /**
     * Sets the value of the tduId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTduId(BigDecimal value) {
        this.tduId = value;
    }

    /**
     * Gets the value of the dtrftId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDtrftId() {
        return dtrftId;
    }

    /**
     * Sets the value of the dtrftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDtrftId(BigDecimal value) {
        this.dtrftId = value;
    }

}
