//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Данные для добавления/изменения записи журнала переноса трафика
 * 
 * <p>Java class for DiscountTransferBasic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscountTransferBasic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}dtlId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}subscriberId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}operDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}mathDtdId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}causeDtdId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}trplId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}disId" minOccurs="0"/&gt;
 *         &lt;element name="startTimeInterval" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="endTimeInterval" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="volBefore" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="volChange" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="volCorrect" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}truleId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}comments" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}dtlIdLink" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}subsIdLink" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}statDtdId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}offerTrplId" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}startPaydDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}endPaydDate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscountTransferBasic", propOrder = {
    "dtlId",
    "subscriberId",
    "operDate",
    "mathDtdId",
    "causeDtdId",
    "trplId",
    "serviceId",
    "disId",
    "startTimeInterval",
    "endTimeInterval",
    "volBefore",
    "volChange",
    "volCorrect",
    "truleId",
    "comments",
    "dtlIdLink",
    "subsIdLink",
    "statDtdId",
    "offerTrplId",
    "startPaydDate",
    "endPaydDate"
})
@XmlSeeAlso({
    DiscountTransfer.class
})
public class DiscountTransferBasic {

    protected BigDecimal dtlId;
    protected BigDecimal subscriberId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operDate;
    protected BigDecimal mathDtdId;
    protected BigDecimal causeDtdId;
    protected BigDecimal trplId;
    protected BigDecimal serviceId;
    protected BigDecimal disId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimeInterval;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTimeInterval;
    protected BigDecimal volBefore;
    protected BigDecimal volChange;
    protected BigDecimal volCorrect;
    protected BigDecimal truleId;
    protected String comments;
    protected BigDecimal dtlIdLink;
    protected BigDecimal subsIdLink;
    protected BigDecimal statDtdId;
    protected BigDecimal offerTrplId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startPaydDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endPaydDate;

    /**
     * Gets the value of the dtlId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDtlId() {
        return dtlId;
    }

    /**
     * Sets the value of the dtlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDtlId(BigDecimal value) {
        this.dtlId = value;
    }

    /**
     * Gets the value of the subscriberId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubscriberId() {
        return subscriberId;
    }

    /**
     * Sets the value of the subscriberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubscriberId(BigDecimal value) {
        this.subscriberId = value;
    }

    /**
     * Gets the value of the operDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperDate() {
        return operDate;
    }

    /**
     * Sets the value of the operDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperDate(XMLGregorianCalendar value) {
        this.operDate = value;
    }

    /**
     * Gets the value of the mathDtdId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMathDtdId() {
        return mathDtdId;
    }

    /**
     * Sets the value of the mathDtdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMathDtdId(BigDecimal value) {
        this.mathDtdId = value;
    }

    /**
     * Gets the value of the causeDtdId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCauseDtdId() {
        return causeDtdId;
    }

    /**
     * Sets the value of the causeDtdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCauseDtdId(BigDecimal value) {
        this.causeDtdId = value;
    }

    /**
     * Gets the value of the trplId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrplId() {
        return trplId;
    }

    /**
     * Sets the value of the trplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrplId(BigDecimal value) {
        this.trplId = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceId(BigDecimal value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the disId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisId() {
        return disId;
    }

    /**
     * Sets the value of the disId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisId(BigDecimal value) {
        this.disId = value;
    }

    /**
     * Gets the value of the startTimeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimeInterval() {
        return startTimeInterval;
    }

    /**
     * Sets the value of the startTimeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeInterval(XMLGregorianCalendar value) {
        this.startTimeInterval = value;
    }

    /**
     * Gets the value of the endTimeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimeInterval() {
        return endTimeInterval;
    }

    /**
     * Sets the value of the endTimeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeInterval(XMLGregorianCalendar value) {
        this.endTimeInterval = value;
    }

    /**
     * Gets the value of the volBefore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolBefore() {
        return volBefore;
    }

    /**
     * Sets the value of the volBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVolBefore(BigDecimal value) {
        this.volBefore = value;
    }

    /**
     * Gets the value of the volChange property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolChange() {
        return volChange;
    }

    /**
     * Sets the value of the volChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVolChange(BigDecimal value) {
        this.volChange = value;
    }

    /**
     * Gets the value of the volCorrect property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolCorrect() {
        return volCorrect;
    }

    /**
     * Sets the value of the volCorrect property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVolCorrect(BigDecimal value) {
        this.volCorrect = value;
    }

    /**
     * Gets the value of the truleId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTruleId() {
        return truleId;
    }

    /**
     * Sets the value of the truleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTruleId(BigDecimal value) {
        this.truleId = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the dtlIdLink property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDtlIdLink() {
        return dtlIdLink;
    }

    /**
     * Sets the value of the dtlIdLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDtlIdLink(BigDecimal value) {
        this.dtlIdLink = value;
    }

    /**
     * Gets the value of the subsIdLink property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubsIdLink() {
        return subsIdLink;
    }

    /**
     * Sets the value of the subsIdLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubsIdLink(BigDecimal value) {
        this.subsIdLink = value;
    }

    /**
     * Gets the value of the statDtdId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStatDtdId() {
        return statDtdId;
    }

    /**
     * Sets the value of the statDtdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStatDtdId(BigDecimal value) {
        this.statDtdId = value;
    }

    /**
     * Gets the value of the offerTrplId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOfferTrplId() {
        return offerTrplId;
    }

    /**
     * Sets the value of the offerTrplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOfferTrplId(BigDecimal value) {
        this.offerTrplId = value;
    }

    /**
     * Gets the value of the startPaydDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartPaydDate() {
        return startPaydDate;
    }

    /**
     * Sets the value of the startPaydDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartPaydDate(XMLGregorianCalendar value) {
        this.startPaydDate = value;
    }

    /**
     * Gets the value of the endPaydDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndPaydDate() {
        return endPaydDate;
    }

    /**
     * Sets the value of the endPaydDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndPaydDate(XMLGregorianCalendar value) {
        this.endPaydDate = value;
    }

}
