//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Тип запроса метода получения профилей тарифных планов
 * 
 * <p>Java class for getRatesRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getRatesRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="branchId" type="{http://www.bercut.com/schema/commonInVoiceAPI}BranchId"/&gt;
 *         &lt;element name="contractName" type="{http://www.bercut.com/cc/sa/ratesmanagement}getRatesContractName"/&gt;
 *         &lt;element name="subscriber" type="{http://www.bercut.com/schema/commonInVoiceAPI}subscriber" minOccurs="0"/&gt;
 *         &lt;element name="trplId" type="{http://www.bercut.com/cc/sa/ratesmanagement}trplId" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="targetDate" type="{http://www.bercut.com/cc/sa/ratesmanagement}targetDate" minOccurs="0"/&gt;
 *         &lt;element name="smstId" type="{http://www.bercut.com/cc/sa/ratesmanagement}smstId" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="serviceId" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="useRegionFilter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="roamTypeId" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="talId" type="{http://www.bercut.com/cc/sa/ratesmanagement}talId" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRatesRequest", namespace = "http://www.bercut.com/cc/sa/ratesmanagement", propOrder = {
    "branchId",
    "contractName",
    "subscriber",
    "trplId",
    "targetDate",
    "smstId",
    "serviceId",
    "useRegionFilter",
    "roamTypeId",
    "talId"
})
public class GetRatesRequest {

    @XmlElement(namespace = "", required = true)
    protected BigDecimal branchId;
    @XmlElement(namespace = "", required = true)
    protected String contractName;
    @XmlElement(namespace = "")
    protected Subscriber subscriber;
    @XmlElement(namespace = "")
    protected List<BigDecimal> trplId;
    @XmlElement(namespace = "")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar targetDate;
    @XmlElement(namespace = "")
    protected List<BigDecimal> smstId;
    @XmlElement(namespace = "")
    protected List<BigDecimal> serviceId;
    @XmlElement(namespace = "")
    protected Boolean useRegionFilter;
    @XmlElement(namespace = "")
    protected List<BigDecimal> roamTypeId;
    @XmlElement(namespace = "")
    protected BigDecimal talId;

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBranchId(BigDecimal value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the contractName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * Sets the value of the contractName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractName(String value) {
        this.contractName = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link Subscriber }
     *     
     */
    public Subscriber getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subscriber }
     *     
     */
    public void setSubscriber(Subscriber value) {
        this.subscriber = value;
    }

    /**
     * Gets the value of the trplId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trplId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrplId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getTrplId() {
        if (trplId == null) {
            trplId = new ArrayList<BigDecimal>();
        }
        return this.trplId;
    }

    /**
     * Gets the value of the targetDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTargetDate() {
        return targetDate;
    }

    /**
     * Sets the value of the targetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTargetDate(XMLGregorianCalendar value) {
        this.targetDate = value;
    }

    /**
     * Gets the value of the smstId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smstId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmstId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getSmstId() {
        if (smstId == null) {
            smstId = new ArrayList<BigDecimal>();
        }
        return this.smstId;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getServiceId() {
        if (serviceId == null) {
            serviceId = new ArrayList<BigDecimal>();
        }
        return this.serviceId;
    }

    /**
     * Gets the value of the useRegionFilter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseRegionFilter() {
        return useRegionFilter;
    }

    /**
     * Sets the value of the useRegionFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseRegionFilter(Boolean value) {
        this.useRegionFilter = value;
    }

    /**
     * Gets the value of the roamTypeId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roamTypeId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoamTypeId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getRoamTypeId() {
        if (roamTypeId == null) {
            roamTypeId = new ArrayList<BigDecimal>();
        }
        return this.roamTypeId;
    }

    /**
     * Gets the value of the talId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTalId() {
        return talId;
    }

    /**
     * Sets the value of the talId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTalId(BigDecimal value) {
        this.talId = value;
    }

}
