//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Правила подключения профилей услуги
 * 
 * <p>Java class for ServiceProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="profId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="profDef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="achmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="pstId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="sTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="eTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="creUserId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="creDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="firstOn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextOn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firstMonth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextMonth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firstOnAdd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextOnAdd" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="acmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="intDictId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="waitPeriodPayment" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="notifyDay" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freePayPeriodFirstOn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freePayPeriodNextOn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="chCheckRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="maxSharedSubs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freeRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="addCheckRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="chAddRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firstPeriodRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextPeriodRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="isChRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="activateInterval" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="payInterval" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="intRemainTime" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="payRemainTimeNotify" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="periodBlockCnt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="checkSubs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="periodBlockPrevCnt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="waitPeriodBlPrev" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}chargeBaseServ" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}countRecipient" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceProfile", propOrder = {
    "profId",
    "profDef",
    "achmId",
    "pstId",
    "sTime",
    "eTime",
    "creUserId",
    "creDate",
    "firstOn",
    "nextOn",
    "firstMonth",
    "nextMonth",
    "firstOnAdd",
    "nextOnAdd",
    "acmId",
    "intDictId",
    "waitPeriodPayment",
    "notifyDay",
    "freePayPeriodFirstOn",
    "freePayPeriodNextOn",
    "chCheckRecipient",
    "maxSharedSubs",
    "freeRecipient",
    "addCheckRecipient",
    "chAddRecipient",
    "firstPeriodRecipient",
    "nextPeriodRecipient",
    "isChRecipient",
    "activateInterval",
    "payInterval",
    "intRemainTime",
    "payRemainTimeNotify",
    "periodBlockCnt",
    "checkSubs",
    "periodBlockPrevCnt",
    "waitPeriodBlPrev",
    "chargeBaseServ",
    "countRecipient"
})
public class ServiceProfile {

    protected BigDecimal profId;
    protected String profDef;
    protected BigDecimal achmId;
    protected BigDecimal pstId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eTime;
    protected BigDecimal creUserId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creDate;
    protected BigDecimal firstOn;
    protected BigDecimal nextOn;
    protected BigDecimal firstMonth;
    protected BigDecimal nextMonth;
    protected BigDecimal firstOnAdd;
    protected BigDecimal nextOnAdd;
    protected BigDecimal acmId;
    protected BigDecimal intDictId;
    protected BigDecimal waitPeriodPayment;
    protected BigDecimal notifyDay;
    protected BigDecimal freePayPeriodFirstOn;
    protected BigDecimal freePayPeriodNextOn;
    protected BigDecimal chCheckRecipient;
    protected BigDecimal maxSharedSubs;
    protected BigDecimal freeRecipient;
    protected BigDecimal addCheckRecipient;
    protected BigDecimal chAddRecipient;
    protected BigDecimal firstPeriodRecipient;
    protected BigDecimal nextPeriodRecipient;
    protected BigDecimal isChRecipient;
    protected BigDecimal activateInterval;
    protected BigDecimal payInterval;
    protected BigDecimal intRemainTime;
    protected BigDecimal payRemainTimeNotify;
    protected BigDecimal periodBlockCnt;
    protected BigDecimal checkSubs;
    protected BigDecimal periodBlockPrevCnt;
    protected BigDecimal waitPeriodBlPrev;
    protected BigDecimal chargeBaseServ;
    protected BigDecimal countRecipient;

    /**
     * Gets the value of the profId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProfId() {
        return profId;
    }

    /**
     * Sets the value of the profId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProfId(BigDecimal value) {
        this.profId = value;
    }

    /**
     * Gets the value of the profDef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfDef() {
        return profDef;
    }

    /**
     * Sets the value of the profDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfDef(String value) {
        this.profDef = value;
    }

    /**
     * Gets the value of the achmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAchmId() {
        return achmId;
    }

    /**
     * Sets the value of the achmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAchmId(BigDecimal value) {
        this.achmId = value;
    }

    /**
     * Gets the value of the pstId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPstId() {
        return pstId;
    }

    /**
     * Sets the value of the pstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPstId(BigDecimal value) {
        this.pstId = value;
    }

    /**
     * Gets the value of the sTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTime() {
        return sTime;
    }

    /**
     * Sets the value of the sTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTime(XMLGregorianCalendar value) {
        this.sTime = value;
    }

    /**
     * Gets the value of the eTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETime() {
        return eTime;
    }

    /**
     * Sets the value of the eTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETime(XMLGregorianCalendar value) {
        this.eTime = value;
    }

    /**
     * Gets the value of the creUserId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreUserId() {
        return creUserId;
    }

    /**
     * Sets the value of the creUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreUserId(BigDecimal value) {
        this.creUserId = value;
    }

    /**
     * Gets the value of the creDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreDate() {
        return creDate;
    }

    /**
     * Sets the value of the creDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreDate(XMLGregorianCalendar value) {
        this.creDate = value;
    }

    /**
     * Gets the value of the firstOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstOn() {
        return firstOn;
    }

    /**
     * Sets the value of the firstOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstOn(BigDecimal value) {
        this.firstOn = value;
    }

    /**
     * Gets the value of the nextOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextOn() {
        return nextOn;
    }

    /**
     * Sets the value of the nextOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextOn(BigDecimal value) {
        this.nextOn = value;
    }

    /**
     * Gets the value of the firstMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstMonth() {
        return firstMonth;
    }

    /**
     * Sets the value of the firstMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstMonth(BigDecimal value) {
        this.firstMonth = value;
    }

    /**
     * Gets the value of the nextMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextMonth() {
        return nextMonth;
    }

    /**
     * Sets the value of the nextMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextMonth(BigDecimal value) {
        this.nextMonth = value;
    }

    /**
     * Gets the value of the firstOnAdd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstOnAdd() {
        return firstOnAdd;
    }

    /**
     * Sets the value of the firstOnAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstOnAdd(BigDecimal value) {
        this.firstOnAdd = value;
    }

    /**
     * Gets the value of the nextOnAdd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextOnAdd() {
        return nextOnAdd;
    }

    /**
     * Sets the value of the nextOnAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextOnAdd(BigDecimal value) {
        this.nextOnAdd = value;
    }

    /**
     * Gets the value of the acmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcmId() {
        return acmId;
    }

    /**
     * Sets the value of the acmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcmId(BigDecimal value) {
        this.acmId = value;
    }

    /**
     * Gets the value of the intDictId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntDictId() {
        return intDictId;
    }

    /**
     * Sets the value of the intDictId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntDictId(BigDecimal value) {
        this.intDictId = value;
    }

    /**
     * Gets the value of the waitPeriodPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaitPeriodPayment() {
        return waitPeriodPayment;
    }

    /**
     * Sets the value of the waitPeriodPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaitPeriodPayment(BigDecimal value) {
        this.waitPeriodPayment = value;
    }

    /**
     * Gets the value of the notifyDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNotifyDay() {
        return notifyDay;
    }

    /**
     * Sets the value of the notifyDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNotifyDay(BigDecimal value) {
        this.notifyDay = value;
    }

    /**
     * Gets the value of the freePayPeriodFirstOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreePayPeriodFirstOn() {
        return freePayPeriodFirstOn;
    }

    /**
     * Sets the value of the freePayPeriodFirstOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreePayPeriodFirstOn(BigDecimal value) {
        this.freePayPeriodFirstOn = value;
    }

    /**
     * Gets the value of the freePayPeriodNextOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreePayPeriodNextOn() {
        return freePayPeriodNextOn;
    }

    /**
     * Sets the value of the freePayPeriodNextOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreePayPeriodNextOn(BigDecimal value) {
        this.freePayPeriodNextOn = value;
    }

    /**
     * Gets the value of the chCheckRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChCheckRecipient() {
        return chCheckRecipient;
    }

    /**
     * Sets the value of the chCheckRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChCheckRecipient(BigDecimal value) {
        this.chCheckRecipient = value;
    }

    /**
     * Gets the value of the maxSharedSubs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxSharedSubs() {
        return maxSharedSubs;
    }

    /**
     * Sets the value of the maxSharedSubs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxSharedSubs(BigDecimal value) {
        this.maxSharedSubs = value;
    }

    /**
     * Gets the value of the freeRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreeRecipient() {
        return freeRecipient;
    }

    /**
     * Sets the value of the freeRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreeRecipient(BigDecimal value) {
        this.freeRecipient = value;
    }

    /**
     * Gets the value of the addCheckRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAddCheckRecipient() {
        return addCheckRecipient;
    }

    /**
     * Sets the value of the addCheckRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAddCheckRecipient(BigDecimal value) {
        this.addCheckRecipient = value;
    }

    /**
     * Gets the value of the chAddRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChAddRecipient() {
        return chAddRecipient;
    }

    /**
     * Sets the value of the chAddRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChAddRecipient(BigDecimal value) {
        this.chAddRecipient = value;
    }

    /**
     * Gets the value of the firstPeriodRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstPeriodRecipient() {
        return firstPeriodRecipient;
    }

    /**
     * Sets the value of the firstPeriodRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstPeriodRecipient(BigDecimal value) {
        this.firstPeriodRecipient = value;
    }

    /**
     * Gets the value of the nextPeriodRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextPeriodRecipient() {
        return nextPeriodRecipient;
    }

    /**
     * Sets the value of the nextPeriodRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextPeriodRecipient(BigDecimal value) {
        this.nextPeriodRecipient = value;
    }

    /**
     * Gets the value of the isChRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsChRecipient() {
        return isChRecipient;
    }

    /**
     * Sets the value of the isChRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsChRecipient(BigDecimal value) {
        this.isChRecipient = value;
    }

    /**
     * Gets the value of the activateInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActivateInterval() {
        return activateInterval;
    }

    /**
     * Sets the value of the activateInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActivateInterval(BigDecimal value) {
        this.activateInterval = value;
    }

    /**
     * Gets the value of the payInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPayInterval() {
        return payInterval;
    }

    /**
     * Sets the value of the payInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPayInterval(BigDecimal value) {
        this.payInterval = value;
    }

    /**
     * Gets the value of the intRemainTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntRemainTime() {
        return intRemainTime;
    }

    /**
     * Sets the value of the intRemainTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntRemainTime(BigDecimal value) {
        this.intRemainTime = value;
    }

    /**
     * Gets the value of the payRemainTimeNotify property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPayRemainTimeNotify() {
        return payRemainTimeNotify;
    }

    /**
     * Sets the value of the payRemainTimeNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPayRemainTimeNotify(BigDecimal value) {
        this.payRemainTimeNotify = value;
    }

    /**
     * Gets the value of the periodBlockCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodBlockCnt() {
        return periodBlockCnt;
    }

    /**
     * Sets the value of the periodBlockCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodBlockCnt(BigDecimal value) {
        this.periodBlockCnt = value;
    }

    /**
     * Gets the value of the checkSubs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCheckSubs() {
        return checkSubs;
    }

    /**
     * Sets the value of the checkSubs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCheckSubs(BigDecimal value) {
        this.checkSubs = value;
    }

    /**
     * Gets the value of the periodBlockPrevCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodBlockPrevCnt() {
        return periodBlockPrevCnt;
    }

    /**
     * Sets the value of the periodBlockPrevCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodBlockPrevCnt(BigDecimal value) {
        this.periodBlockPrevCnt = value;
    }

    /**
     * Gets the value of the waitPeriodBlPrev property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaitPeriodBlPrev() {
        return waitPeriodBlPrev;
    }

    /**
     * Sets the value of the waitPeriodBlPrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaitPeriodBlPrev(BigDecimal value) {
        this.waitPeriodBlPrev = value;
    }

    /**
     * Gets the value of the chargeBaseServ property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeBaseServ() {
        return chargeBaseServ;
    }

    /**
     * Sets the value of the chargeBaseServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeBaseServ(BigDecimal value) {
        this.chargeBaseServ = value;
    }

    /**
     * Gets the value of the countRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCountRecipient() {
        return countRecipient;
    }

    /**
     * Sets the value of the countRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCountRecipient(BigDecimal value) {
        this.countRecipient = value;
    }

}
