//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Список состояний распаковки услуг из продуктового семейства “Спящий пакет”
 * 
 * <p>Java class for SleepingPck complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SleepingPck"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subsId" type="{http://www.bercut.com/schema/commonInVoiceAPI}subscriberId" minOccurs="0"/&gt;
 *         &lt;element name="servId" type="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId" minOccurs="0"/&gt;
 *         &lt;element name="sstat" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="startChrgInterval" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="endChrgInterval" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="chargeQuantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="lastChrgDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="chargeQuantityMax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SleepingPck", propOrder = {
    "subsId",
    "servId",
    "sstat",
    "startChrgInterval",
    "endChrgInterval",
    "chargeQuantity",
    "lastChrgDate",
    "chargeQuantityMax"
})
public class SleepingPck {

    protected BigDecimal subsId;
    protected BigDecimal servId;
    protected BigDecimal sstat;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startChrgInterval;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endChrgInterval;
    protected BigDecimal chargeQuantity;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastChrgDate;
    protected BigDecimal chargeQuantityMax;

    /**
     * Gets the value of the subsId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubsId() {
        return subsId;
    }

    /**
     * Sets the value of the subsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubsId(BigDecimal value) {
        this.subsId = value;
    }

    /**
     * Gets the value of the servId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServId() {
        return servId;
    }

    /**
     * Sets the value of the servId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServId(BigDecimal value) {
        this.servId = value;
    }

    /**
     * Gets the value of the sstat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSstat() {
        return sstat;
    }

    /**
     * Sets the value of the sstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSstat(BigDecimal value) {
        this.sstat = value;
    }

    /**
     * Gets the value of the startChrgInterval property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartChrgInterval() {
        return startChrgInterval;
    }

    /**
     * Sets the value of the startChrgInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartChrgInterval(XMLGregorianCalendar value) {
        this.startChrgInterval = value;
    }

    /**
     * Gets the value of the endChrgInterval property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndChrgInterval() {
        return endChrgInterval;
    }

    /**
     * Sets the value of the endChrgInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndChrgInterval(XMLGregorianCalendar value) {
        this.endChrgInterval = value;
    }

    /**
     * Gets the value of the chargeQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeQuantity() {
        return chargeQuantity;
    }

    /**
     * Sets the value of the chargeQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeQuantity(BigDecimal value) {
        this.chargeQuantity = value;
    }

    /**
     * Gets the value of the lastChrgDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastChrgDate() {
        return lastChrgDate;
    }

    /**
     * Sets the value of the lastChrgDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastChrgDate(XMLGregorianCalendar value) {
        this.lastChrgDate = value;
    }

    /**
     * Gets the value of the chargeQuantityMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeQuantityMax() {
        return chargeQuantityMax;
    }

    /**
     * Sets the value of the chargeQuantityMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeQuantityMax(BigDecimal value) {
        this.chargeQuantityMax = value;
    }

}
