//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Набор параметров скидки абонента
 * 
 * <p>Java class for SubscriberDiscount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriberDiscount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="disId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="disName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vol1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="vol2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="lastDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="dvtpId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dvtpName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="prevLevel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextLevel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="sTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}sDate" minOccurs="0"/&gt;
 *         &lt;element name="eTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}eDate" minOccurs="0"/&gt;
 *         &lt;element name="servId" type="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId" minOccurs="0"/&gt;
 *         &lt;element name="distId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="timeOffset" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="currentInterval" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dtrftId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dtrftName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rQuota" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dSubsId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dVol1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dNextLevel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dVol2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dDisId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="profId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="currentProfId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="persNextLevel" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriberDiscount", propOrder = {
    "disId",
    "disName",
    "vol1",
    "vol2",
    "lastDate",
    "dvtpId",
    "dvtpName",
    "prevLevel",
    "nextLevel",
    "sTime",
    "eTime",
    "servId",
    "distId",
    "timeOffset",
    "currentInterval",
    "dtrftId",
    "dtrftName",
    "rQuota",
    "dSubsId",
    "dVol1",
    "dNextLevel",
    "dVol2",
    "dDisId",
    "profId",
    "currentProfId",
    "persNextLevel"
})
public class SubscriberDiscount {

    protected BigDecimal disId;
    protected String disName;
    protected BigDecimal vol1;
    protected BigDecimal vol2;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastDate;
    protected BigDecimal dvtpId;
    protected String dvtpName;
    protected BigDecimal prevLevel;
    protected BigDecimal nextLevel;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eTime;
    protected BigDecimal servId;
    protected BigDecimal distId;
    protected BigDecimal timeOffset;
    protected BigDecimal currentInterval;
    protected BigDecimal dtrftId;
    protected String dtrftName;
    protected BigDecimal rQuota;
    protected BigDecimal dSubsId;
    protected BigDecimal dVol1;
    protected BigDecimal dNextLevel;
    protected BigDecimal dVol2;
    protected BigDecimal dDisId;
    protected BigDecimal profId;
    protected BigDecimal currentProfId;
    protected BigDecimal persNextLevel;

    /**
     * Gets the value of the disId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisId() {
        return disId;
    }

    /**
     * Sets the value of the disId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisId(BigDecimal value) {
        this.disId = value;
    }

    /**
     * Gets the value of the disName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisName() {
        return disName;
    }

    /**
     * Sets the value of the disName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisName(String value) {
        this.disName = value;
    }

    /**
     * Gets the value of the vol1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVol1() {
        return vol1;
    }

    /**
     * Sets the value of the vol1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVol1(BigDecimal value) {
        this.vol1 = value;
    }

    /**
     * Gets the value of the vol2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVol2() {
        return vol2;
    }

    /**
     * Sets the value of the vol2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVol2(BigDecimal value) {
        this.vol2 = value;
    }

    /**
     * Gets the value of the lastDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastDate() {
        return lastDate;
    }

    /**
     * Sets the value of the lastDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastDate(XMLGregorianCalendar value) {
        this.lastDate = value;
    }

    /**
     * Gets the value of the dvtpId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDvtpId() {
        return dvtpId;
    }

    /**
     * Sets the value of the dvtpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDvtpId(BigDecimal value) {
        this.dvtpId = value;
    }

    /**
     * Gets the value of the dvtpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDvtpName() {
        return dvtpName;
    }

    /**
     * Sets the value of the dvtpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDvtpName(String value) {
        this.dvtpName = value;
    }

    /**
     * Gets the value of the prevLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevLevel() {
        return prevLevel;
    }

    /**
     * Sets the value of the prevLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevLevel(BigDecimal value) {
        this.prevLevel = value;
    }

    /**
     * Gets the value of the nextLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextLevel() {
        return nextLevel;
    }

    /**
     * Sets the value of the nextLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextLevel(BigDecimal value) {
        this.nextLevel = value;
    }

    /**
     * Gets the value of the sTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTime() {
        return sTime;
    }

    /**
     * Sets the value of the sTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTime(XMLGregorianCalendar value) {
        this.sTime = value;
    }

    /**
     * Gets the value of the eTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETime() {
        return eTime;
    }

    /**
     * Sets the value of the eTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETime(XMLGregorianCalendar value) {
        this.eTime = value;
    }

    /**
     * Gets the value of the servId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServId() {
        return servId;
    }

    /**
     * Sets the value of the servId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServId(BigDecimal value) {
        this.servId = value;
    }

    /**
     * Gets the value of the distId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistId() {
        return distId;
    }

    /**
     * Sets the value of the distId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistId(BigDecimal value) {
        this.distId = value;
    }

    /**
     * Gets the value of the timeOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimeOffset() {
        return timeOffset;
    }

    /**
     * Sets the value of the timeOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimeOffset(BigDecimal value) {
        this.timeOffset = value;
    }

    /**
     * Gets the value of the currentInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentInterval() {
        return currentInterval;
    }

    /**
     * Sets the value of the currentInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentInterval(BigDecimal value) {
        this.currentInterval = value;
    }

    /**
     * Gets the value of the dtrftId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDtrftId() {
        return dtrftId;
    }

    /**
     * Sets the value of the dtrftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDtrftId(BigDecimal value) {
        this.dtrftId = value;
    }

    /**
     * Gets the value of the dtrftName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtrftName() {
        return dtrftName;
    }

    /**
     * Sets the value of the dtrftName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtrftName(String value) {
        this.dtrftName = value;
    }

    /**
     * Gets the value of the rQuota property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRQuota() {
        return rQuota;
    }

    /**
     * Sets the value of the rQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRQuota(BigDecimal value) {
        this.rQuota = value;
    }

    /**
     * Gets the value of the dSubsId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDSubsId() {
        return dSubsId;
    }

    /**
     * Sets the value of the dSubsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDSubsId(BigDecimal value) {
        this.dSubsId = value;
    }

    /**
     * Gets the value of the dVol1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDVol1() {
        return dVol1;
    }

    /**
     * Sets the value of the dVol1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDVol1(BigDecimal value) {
        this.dVol1 = value;
    }

    /**
     * Gets the value of the dNextLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDNextLevel() {
        return dNextLevel;
    }

    /**
     * Sets the value of the dNextLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDNextLevel(BigDecimal value) {
        this.dNextLevel = value;
    }

    /**
     * Gets the value of the dVol2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDVol2() {
        return dVol2;
    }

    /**
     * Sets the value of the dVol2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDVol2(BigDecimal value) {
        this.dVol2 = value;
    }

    /**
     * Gets the value of the dDisId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDDisId() {
        return dDisId;
    }

    /**
     * Sets the value of the dDisId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDDisId(BigDecimal value) {
        this.dDisId = value;
    }

    /**
     * Gets the value of the profId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProfId() {
        return profId;
    }

    /**
     * Sets the value of the profId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProfId(BigDecimal value) {
        this.profId = value;
    }

    /**
     * Gets the value of the currentProfId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentProfId() {
        return currentProfId;
    }

    /**
     * Sets the value of the currentProfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentProfId(BigDecimal value) {
        this.currentProfId = value;
    }

    /**
     * Gets the value of the persNextLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPersNextLevel() {
        return persNextLevel;
    }

    /**
     * Sets the value of the persNextLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPersNextLevel(BigDecimal value) {
        this.persNextLevel = value;
    }

}
