//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriberTypeName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SubscriberTypeName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="prepaid"/&gt;
 *     &lt;enumeration value="postpaid"/&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SubscriberTypeName")
@XmlEnum
public enum SubscriberTypeName {


    /**
     * Абонента оплачивает услуги перед использованием
     * 
     */
    @XmlEnumValue("prepaid")
    PREPAID("prepaid"),

    /**
     * Абонента оплачивает услуги после использования
     * 
     */
    @XmlEnumValue("postpaid")
    POSTPAID("postpaid"),

    /**
     * Неизвестный
     * 
     */
    @XmlEnumValue("undefined")
    UNDEFINED("undefined");
    private final String value;

    SubscriberTypeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubscriberTypeName fromValue(String v) {
        for (SubscriberTypeName c: SubscriberTypeName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
