//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.wsdl.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Исторический набор параметров тирифного плана
 * 
 * <p>Java class for TarifHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TarifHistory"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="trplId" type="{http://www.bercut.com/schema/commonInVoiceAPI}trplId" minOccurs="0"/&gt;
 *         &lt;element name="numHistory" type="{http://www.bercut.com/schema/commonInVoiceAPI}numberHistory" minOccurs="0"/&gt;
 *         &lt;element name="smstId" type="{http://www.bercut.com/schema/commonInVoiceAPI}smstId" minOccurs="0"/&gt;
 *         &lt;element name="sTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}sDate" minOccurs="0"/&gt;
 *         &lt;element name="eTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}eDate" minOccurs="0"/&gt;
 *         &lt;element name="localMul" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="mmtMul" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="branchId" type="{http://www.bercut.com/schema/commonInVoiceAPI}BranchId" minOccurs="0"/&gt;
 *         &lt;element name="connectServId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="timezoneTclsTrpl" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freeSecCount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="isSpecial" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TarifHistory", propOrder = {
    "trplId",
    "numHistory",
    "smstId",
    "sTime",
    "eTime",
    "localMul",
    "mmtMul",
    "branchId",
    "connectServId",
    "timezoneTclsTrpl",
    "freeSecCount",
    "isSpecial"
})
public class TarifHistory {

    protected BigDecimal trplId;
    protected BigDecimal numHistory;
    protected BigDecimal smstId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eTime;
    protected BigDecimal localMul;
    protected BigDecimal mmtMul;
    protected BigDecimal branchId;
    protected BigDecimal connectServId;
    protected BigDecimal timezoneTclsTrpl;
    protected BigDecimal freeSecCount;
    protected BigDecimal isSpecial;

    /**
     * Gets the value of the trplId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrplId() {
        return trplId;
    }

    /**
     * Sets the value of the trplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrplId(BigDecimal value) {
        this.trplId = value;
    }

    /**
     * Gets the value of the numHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumHistory() {
        return numHistory;
    }

    /**
     * Sets the value of the numHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumHistory(BigDecimal value) {
        this.numHistory = value;
    }

    /**
     * Gets the value of the smstId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSmstId() {
        return smstId;
    }

    /**
     * Sets the value of the smstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSmstId(BigDecimal value) {
        this.smstId = value;
    }

    /**
     * Gets the value of the sTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTime() {
        return sTime;
    }

    /**
     * Sets the value of the sTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTime(XMLGregorianCalendar value) {
        this.sTime = value;
    }

    /**
     * Gets the value of the eTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETime() {
        return eTime;
    }

    /**
     * Sets the value of the eTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETime(XMLGregorianCalendar value) {
        this.eTime = value;
    }

    /**
     * Gets the value of the localMul property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLocalMul() {
        return localMul;
    }

    /**
     * Sets the value of the localMul property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLocalMul(BigDecimal value) {
        this.localMul = value;
    }

    /**
     * Gets the value of the mmtMul property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMmtMul() {
        return mmtMul;
    }

    /**
     * Sets the value of the mmtMul property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMmtMul(BigDecimal value) {
        this.mmtMul = value;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBranchId(BigDecimal value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the connectServId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConnectServId() {
        return connectServId;
    }

    /**
     * Sets the value of the connectServId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConnectServId(BigDecimal value) {
        this.connectServId = value;
    }

    /**
     * Gets the value of the timezoneTclsTrpl property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimezoneTclsTrpl() {
        return timezoneTclsTrpl;
    }

    /**
     * Sets the value of the timezoneTclsTrpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimezoneTclsTrpl(BigDecimal value) {
        this.timezoneTclsTrpl = value;
    }

    /**
     * Gets the value of the freeSecCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreeSecCount() {
        return freeSecCount;
    }

    /**
     * Sets the value of the freeSecCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreeSecCount(BigDecimal value) {
        this.freeSecCount = value;
    }

    /**
     * Gets the value of the isSpecial property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsSpecial() {
        return isSpecial;
    }

    /**
     * Sets the value of the isSpecial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsSpecial(BigDecimal value) {
        this.isSpecial = value;
    }

}
