//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Платеж клиента
 * 
 * <p>Java class for ClientPayment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientPayment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="paymentId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="paymentDocId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="clientBalanceId" type="{http://www.bercut.com/schema/commonInVoiceAPI}balanceId" minOccurs="0"/&gt;
 *         &lt;element name="clientId" type="{http://www.bercut.com/schema/commonInVoiceAPI}clientId" minOccurs="0"/&gt;
 *         &lt;element name="paytId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="promisePayDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="summ" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="currId" type="{http://www.bercut.com/schema/commonInVoiceAPI}currencyId" minOccurs="0"/&gt;
 *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="summRub" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nspRub" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="usedPayValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="subscriberId" type="{http://www.bercut.com/schema/commonInVoiceAPI}subscriberId" minOccurs="0"/&gt;
 *         &lt;element name="obId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="chargeId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="rateBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="delDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="promiseDelDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="deadDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="dmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="paymentTypeId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="paymentDocTypeId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="cnt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="parentPayId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="paymentDocDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="pPayParam" type="{http://www.bercut.com/schema/commonInVoiceAPI}PromisePayParams" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientPayment", propOrder = {
    "paymentId",
    "paymentDocId",
    "clientBalanceId",
    "clientId",
    "paytId",
    "paymentDate",
    "promisePayDate",
    "summ",
    "currId",
    "rate",
    "summRub",
    "nspRub",
    "usedPayValue",
    "subscriberId",
    "obId",
    "chargeId",
    "rateBalance",
    "delDate",
    "promiseDelDate",
    "deadDate",
    "dmId",
    "paymentTypeId",
    "paymentDocTypeId",
    "cnt",
    "parentPayId",
    "paymentDocDate",
    "pPayParam"
})
public class ClientPayment {

    protected BigDecimal paymentId;
    protected BigDecimal paymentDocId;
    protected BigDecimal clientBalanceId;
    protected BigDecimal clientId;
    protected BigDecimal paytId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar promisePayDate;
    protected BigDecimal summ;
    protected BigDecimal currId;
    protected BigDecimal rate;
    protected BigDecimal summRub;
    protected BigDecimal nspRub;
    protected BigDecimal usedPayValue;
    protected BigDecimal subscriberId;
    protected BigDecimal obId;
    protected BigDecimal chargeId;
    protected BigDecimal rateBalance;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar delDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar promiseDelDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deadDate;
    protected BigDecimal dmId;
    protected BigDecimal paymentTypeId;
    protected BigDecimal paymentDocTypeId;
    protected BigDecimal cnt;
    protected BigDecimal parentPayId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentDocDate;
    protected List<PromisePayParams> pPayParam;

    /**
     * Gets the value of the paymentId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentId() {
        return paymentId;
    }

    /**
     * Sets the value of the paymentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentId(BigDecimal value) {
        this.paymentId = value;
    }

    /**
     * Gets the value of the paymentDocId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentDocId() {
        return paymentDocId;
    }

    /**
     * Sets the value of the paymentDocId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentDocId(BigDecimal value) {
        this.paymentDocId = value;
    }

    /**
     * Gets the value of the clientBalanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClientBalanceId() {
        return clientBalanceId;
    }

    /**
     * Sets the value of the clientBalanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClientBalanceId(BigDecimal value) {
        this.clientBalanceId = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClientId(BigDecimal value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the paytId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaytId() {
        return paytId;
    }

    /**
     * Sets the value of the paytId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaytId(BigDecimal value) {
        this.paytId = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDate(XMLGregorianCalendar value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the promisePayDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPromisePayDate() {
        return promisePayDate;
    }

    /**
     * Sets the value of the promisePayDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPromisePayDate(XMLGregorianCalendar value) {
        this.promisePayDate = value;
    }

    /**
     * Gets the value of the summ property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSumm() {
        return summ;
    }

    /**
     * Sets the value of the summ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSumm(BigDecimal value) {
        this.summ = value;
    }

    /**
     * Gets the value of the currId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrId() {
        return currId;
    }

    /**
     * Sets the value of the currId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrId(BigDecimal value) {
        this.currId = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRate(BigDecimal value) {
        this.rate = value;
    }

    /**
     * Gets the value of the summRub property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSummRub() {
        return summRub;
    }

    /**
     * Sets the value of the summRub property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSummRub(BigDecimal value) {
        this.summRub = value;
    }

    /**
     * Gets the value of the nspRub property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNspRub() {
        return nspRub;
    }

    /**
     * Sets the value of the nspRub property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNspRub(BigDecimal value) {
        this.nspRub = value;
    }

    /**
     * Gets the value of the usedPayValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUsedPayValue() {
        return usedPayValue;
    }

    /**
     * Sets the value of the usedPayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUsedPayValue(BigDecimal value) {
        this.usedPayValue = value;
    }

    /**
     * Gets the value of the subscriberId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubscriberId() {
        return subscriberId;
    }

    /**
     * Sets the value of the subscriberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubscriberId(BigDecimal value) {
        this.subscriberId = value;
    }

    /**
     * Gets the value of the obId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getObId() {
        return obId;
    }

    /**
     * Sets the value of the obId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setObId(BigDecimal value) {
        this.obId = value;
    }

    /**
     * Gets the value of the chargeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeId() {
        return chargeId;
    }

    /**
     * Sets the value of the chargeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeId(BigDecimal value) {
        this.chargeId = value;
    }

    /**
     * Gets the value of the rateBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateBalance() {
        return rateBalance;
    }

    /**
     * Sets the value of the rateBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateBalance(BigDecimal value) {
        this.rateBalance = value;
    }

    /**
     * Gets the value of the delDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDelDate() {
        return delDate;
    }

    /**
     * Sets the value of the delDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDelDate(XMLGregorianCalendar value) {
        this.delDate = value;
    }

    /**
     * Gets the value of the promiseDelDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPromiseDelDate() {
        return promiseDelDate;
    }

    /**
     * Sets the value of the promiseDelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPromiseDelDate(XMLGregorianCalendar value) {
        this.promiseDelDate = value;
    }

    /**
     * Gets the value of the deadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeadDate() {
        return deadDate;
    }

    /**
     * Sets the value of the deadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeadDate(XMLGregorianCalendar value) {
        this.deadDate = value;
    }

    /**
     * Gets the value of the dmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDmId() {
        return dmId;
    }

    /**
     * Sets the value of the dmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDmId(BigDecimal value) {
        this.dmId = value;
    }

    /**
     * Gets the value of the paymentTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentTypeId() {
        return paymentTypeId;
    }

    /**
     * Sets the value of the paymentTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentTypeId(BigDecimal value) {
        this.paymentTypeId = value;
    }

    /**
     * Gets the value of the paymentDocTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaymentDocTypeId() {
        return paymentDocTypeId;
    }

    /**
     * Sets the value of the paymentDocTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaymentDocTypeId(BigDecimal value) {
        this.paymentDocTypeId = value;
    }

    /**
     * Gets the value of the cnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCnt() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCnt(BigDecimal value) {
        this.cnt = value;
    }

    /**
     * Gets the value of the parentPayId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParentPayId() {
        return parentPayId;
    }

    /**
     * Sets the value of the parentPayId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParentPayId(BigDecimal value) {
        this.parentPayId = value;
    }

    /**
     * Gets the value of the paymentDocDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDocDate() {
        return paymentDocDate;
    }

    /**
     * Sets the value of the paymentDocDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDocDate(XMLGregorianCalendar value) {
        this.paymentDocDate = value;
    }

    /**
     * Gets the value of the pPayParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pPayParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPPayParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PromisePayParams }
     * 
     * 
     */
    public List<PromisePayParams> getPPayParam() {
        if (pPayParam == null) {
            pPayParam = new ArrayList<PromisePayParams>();
        }
        return this.pPayParam;
    }

}
