//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Действия, назначенные к выполнению на достижение порогов модификатора
 * 
 * <p>Java class for DiscountLvlAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscountLvlAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dis_id" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="discount_level" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="disact_id" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="charging_mode" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="num_history" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="sTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}sDate"/&gt;
 *         &lt;element name="eTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}eDate"/&gt;
 *         &lt;element name="smst_id" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="cre_user_id" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="cre_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="branch_id" type="{http://www.bercut.com/schema/commonInVoiceAPI}BranchId"/&gt;
 *         &lt;element name="trpl_id" type="{http://www.bercut.com/schema/commonInVoiceAPI}trplId"/&gt;
 *         &lt;element name="int_param1" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="serviceId" type="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId"/&gt;
 *         &lt;element name="act_action" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dactype_id" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}areaId" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscountLvlAction", propOrder = {
    "disId",
    "discountLevel",
    "disactId",
    "chargingMode",
    "numHistory",
    "sTime",
    "eTime",
    "smstId",
    "creUserId",
    "creDate",
    "branchId",
    "trplId",
    "intParam1",
    "serviceId",
    "actAction",
    "dactypeId",
    "areaId"
})
public class DiscountLvlAction {

    @XmlElement(name = "dis_id", required = true)
    protected BigDecimal disId;
    @XmlElement(name = "discount_level", required = true)
    protected BigDecimal discountLevel;
    @XmlElement(name = "disact_id", required = true)
    protected BigDecimal disactId;
    @XmlElement(name = "charging_mode", required = true)
    protected BigDecimal chargingMode;
    @XmlElement(name = "num_history", required = true)
    protected BigDecimal numHistory;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eTime;
    @XmlElement(name = "smst_id", required = true)
    protected BigDecimal smstId;
    @XmlElement(name = "cre_user_id", required = true)
    protected BigDecimal creUserId;
    @XmlElement(name = "cre_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creDate;
    @XmlElement(name = "branch_id", required = true)
    protected BigDecimal branchId;
    @XmlElement(name = "trpl_id", required = true)
    protected BigDecimal trplId;
    @XmlElement(name = "int_param1", required = true)
    protected BigDecimal intParam1;
    @XmlElement(required = true)
    protected BigDecimal serviceId;
    @XmlElement(name = "act_action")
    protected String actAction;
    @XmlElement(name = "dactype_id")
    protected BigDecimal dactypeId;
    protected BigDecimal areaId;

    /**
     * Gets the value of the disId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisId() {
        return disId;
    }

    /**
     * Sets the value of the disId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisId(BigDecimal value) {
        this.disId = value;
    }

    /**
     * Gets the value of the discountLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountLevel() {
        return discountLevel;
    }

    /**
     * Sets the value of the discountLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountLevel(BigDecimal value) {
        this.discountLevel = value;
    }

    /**
     * Gets the value of the disactId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisactId() {
        return disactId;
    }

    /**
     * Sets the value of the disactId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisactId(BigDecimal value) {
        this.disactId = value;
    }

    /**
     * Gets the value of the chargingMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargingMode() {
        return chargingMode;
    }

    /**
     * Sets the value of the chargingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargingMode(BigDecimal value) {
        this.chargingMode = value;
    }

    /**
     * Gets the value of the numHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumHistory() {
        return numHistory;
    }

    /**
     * Sets the value of the numHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumHistory(BigDecimal value) {
        this.numHistory = value;
    }

    /**
     * Gets the value of the sTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTime() {
        return sTime;
    }

    /**
     * Sets the value of the sTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTime(XMLGregorianCalendar value) {
        this.sTime = value;
    }

    /**
     * Gets the value of the eTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETime() {
        return eTime;
    }

    /**
     * Sets the value of the eTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETime(XMLGregorianCalendar value) {
        this.eTime = value;
    }

    /**
     * Gets the value of the smstId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSmstId() {
        return smstId;
    }

    /**
     * Sets the value of the smstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSmstId(BigDecimal value) {
        this.smstId = value;
    }

    /**
     * Gets the value of the creUserId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreUserId() {
        return creUserId;
    }

    /**
     * Sets the value of the creUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreUserId(BigDecimal value) {
        this.creUserId = value;
    }

    /**
     * Gets the value of the creDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreDate() {
        return creDate;
    }

    /**
     * Sets the value of the creDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreDate(XMLGregorianCalendar value) {
        this.creDate = value;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBranchId(BigDecimal value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the trplId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrplId() {
        return trplId;
    }

    /**
     * Sets the value of the trplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrplId(BigDecimal value) {
        this.trplId = value;
    }

    /**
     * Gets the value of the intParam1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntParam1() {
        return intParam1;
    }

    /**
     * Sets the value of the intParam1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntParam1(BigDecimal value) {
        this.intParam1 = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceId(BigDecimal value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the actAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActAction() {
        return actAction;
    }

    /**
     * Sets the value of the actAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActAction(String value) {
        this.actAction = value;
    }

    /**
     * Gets the value of the dactypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDactypeId() {
        return dactypeId;
    }

    /**
     * Sets the value of the dactypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDactypeId(BigDecimal value) {
        this.dactypeId = value;
    }

    /**
     * Gets the value of the areaId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAreaId(BigDecimal value) {
        this.areaId = value;
    }

}
