//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Данные по истории телефонного номера
 * 
 * <p>Java class for PhoneHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhoneHistory"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="phnId" type="{http://www.bercut.com/schema/commonInVoiceAPI}phnId" minOccurs="0"/&gt;
 *         &lt;element name="phoneId" type="{http://www.bercut.com/schema/commonInVoiceAPI}phoneId" minOccurs="0"/&gt;
 *         &lt;element name="numberHistory" type="{http://www.bercut.com/schema/commonInVoiceAPI}numberHistory" minOccurs="0"/&gt;
 *         &lt;element name="phsId" type="{http://www.bercut.com/schema/commonInVoiceAPI}phsId" minOccurs="0"/&gt;
 *         &lt;element name="sTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}sDate" minOccurs="0"/&gt;
 *         &lt;element name="eTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}eDate" minOccurs="0"/&gt;
 *         &lt;element name="phtId" type="{http://www.bercut.com/schema/commonInVoiceAPI}phtId" minOccurs="0"/&gt;
 *         &lt;element name="switchId" type="{http://www.bercut.com/schema/commonInVoiceAPI}switchId" minOccurs="0"/&gt;
 *         &lt;element name="branchId" type="{http://www.bercut.com/schema/commonInVoiceAPI}BranchId" minOccurs="0"/&gt;
 *         &lt;element name="dlrId" type="{http://www.bercut.com/schema/commonInVoiceAPI}dlrId" minOccurs="0"/&gt;
 *         &lt;element name="phcId" type="{http://www.bercut.com/schema/commonInVoiceAPI}phcId" minOccurs="0"/&gt;
 *         &lt;element name="pstatId" type="{http://www.bercut.com/schema/commonInVoiceAPI}pstatId" minOccurs="0"/&gt;
 *         &lt;element name="holder" type="{http://www.bercut.com/schema/commonInVoiceAPI}holder" minOccurs="0"/&gt;
 *         &lt;element name="donor" type="{http://www.bercut.com/schema/commonInVoiceAPI}donor" minOccurs="0"/&gt;
 *         &lt;element name="recipient" type="{http://www.bercut.com/schema/commonInVoiceAPI}recipient" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneHistory", propOrder = {
    "phnId",
    "phoneId",
    "numberHistory",
    "phsId",
    "sTime",
    "eTime",
    "phtId",
    "switchId",
    "branchId",
    "dlrId",
    "phcId",
    "pstatId",
    "holder",
    "donor",
    "recipient"
})
public class PhoneHistory {

    protected BigDecimal phnId;
    protected BigDecimal phoneId;
    protected BigDecimal numberHistory;
    protected BigDecimal phsId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eTime;
    protected BigDecimal phtId;
    protected BigDecimal switchId;
    protected BigDecimal branchId;
    protected BigDecimal dlrId;
    protected BigDecimal phcId;
    protected BigDecimal pstatId;
    protected String holder;
    protected String donor;
    protected String recipient;

    /**
     * Gets the value of the phnId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPhnId() {
        return phnId;
    }

    /**
     * Sets the value of the phnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPhnId(BigDecimal value) {
        this.phnId = value;
    }

    /**
     * Gets the value of the phoneId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPhoneId() {
        return phoneId;
    }

    /**
     * Sets the value of the phoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPhoneId(BigDecimal value) {
        this.phoneId = value;
    }

    /**
     * Gets the value of the numberHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumberHistory() {
        return numberHistory;
    }

    /**
     * Sets the value of the numberHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumberHistory(BigDecimal value) {
        this.numberHistory = value;
    }

    /**
     * Gets the value of the phsId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPhsId() {
        return phsId;
    }

    /**
     * Sets the value of the phsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPhsId(BigDecimal value) {
        this.phsId = value;
    }

    /**
     * Gets the value of the sTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSTime() {
        return sTime;
    }

    /**
     * Sets the value of the sTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSTime(XMLGregorianCalendar value) {
        this.sTime = value;
    }

    /**
     * Gets the value of the eTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETime() {
        return eTime;
    }

    /**
     * Sets the value of the eTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETime(XMLGregorianCalendar value) {
        this.eTime = value;
    }

    /**
     * Gets the value of the phtId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPhtId() {
        return phtId;
    }

    /**
     * Sets the value of the phtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPhtId(BigDecimal value) {
        this.phtId = value;
    }

    /**
     * Gets the value of the switchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSwitchId() {
        return switchId;
    }

    /**
     * Sets the value of the switchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSwitchId(BigDecimal value) {
        this.switchId = value;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBranchId(BigDecimal value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the dlrId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDlrId() {
        return dlrId;
    }

    /**
     * Sets the value of the dlrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDlrId(BigDecimal value) {
        this.dlrId = value;
    }

    /**
     * Gets the value of the phcId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPhcId() {
        return phcId;
    }

    /**
     * Sets the value of the phcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPhcId(BigDecimal value) {
        this.phcId = value;
    }

    /**
     * Gets the value of the pstatId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPstatId() {
        return pstatId;
    }

    /**
     * Sets the value of the pstatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPstatId(BigDecimal value) {
        this.pstatId = value;
    }

    /**
     * Gets the value of the holder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHolder() {
        return holder;
    }

    /**
     * Sets the value of the holder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHolder(String value) {
        this.holder = value;
    }

    /**
     * Gets the value of the donor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDonor() {
        return donor;
    }

    /**
     * Sets the value of the donor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDonor(String value) {
        this.donor = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipient(String value) {
        this.recipient = value;
    }

}
