//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Набор информационных параметров услуги
 * 
 * <p>Java class for ServiceInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serviceName" type="{http://www.bercut.com/schema/commonInVoiceAPI}ServiceName" minOccurs="0"/&gt;
 *         &lt;element name="serviceId" type="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId" minOccurs="0"/&gt;
 *         &lt;element name="serviceTypeName" type="{http://www.bercut.com/schema/commonInVoiceAPI}ServiceTypeName" minOccurs="0"/&gt;
 *         &lt;element name="serviceTypeId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firstOn" type="{http://www.bercut.com/schema/commonInVoiceAPI}firstOn" minOccurs="0"/&gt;
 *         &lt;element name="nextOn" type="{http://www.bercut.com/schema/commonInVoiceAPI}nextOn" minOccurs="0"/&gt;
 *         &lt;element name="firstMonth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextMonth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="trplId" type="{http://www.bercut.com/schema/commonInVoiceAPI}trplId" minOccurs="0"/&gt;
 *         &lt;element name="serviceSettings" type="{http://www.bercut.com/schema/commonInVoiceAPI}ServiceSettingList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="param1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="trpkId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="acmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firstOnAdd" type="{http://www.bercut.com/schema/commonInVoiceAPI}firstOnAdd" minOccurs="0"/&gt;
 *         &lt;element name="nextOnAdd" type="{http://www.bercut.com/schema/commonInVoiceAPI}nextOnAdd" minOccurs="0"/&gt;
 *         &lt;element name="intDictId" type="{http://www.bercut.com/schema/commonInVoiceAPI}intDictId" minOccurs="0"/&gt;
 *         &lt;element name="waitPeriodPayment" type="{http://www.bercut.com/schema/commonInVoiceAPI}waitPeriodPayment" minOccurs="0"/&gt;
 *         &lt;element name="notifyDay" type="{http://www.bercut.com/schema/commonInVoiceAPI}notifyDay" minOccurs="0"/&gt;
 *         &lt;element name="manageServ" type="{http://www.bercut.com/schema/commonInVoiceAPI}manageServ" minOccurs="0"/&gt;
 *         &lt;element name="baseServId" type="{http://www.bercut.com/schema/commonInVoiceAPI}baseServId" minOccurs="0"/&gt;
 *         &lt;element name="sgId" type="{http://www.bercut.com/schema/commonInVoiceAPI}sgId" minOccurs="0"/&gt;
 *         &lt;element name="bsgId" type="{http://www.bercut.com/schema/commonInVoiceAPI}bsgId" minOccurs="0"/&gt;
 *         &lt;element name="isShared" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="maxSharedSubs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="achmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="isBasic" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="productFamily" type="{http://www.bercut.com/schema/commonInVoiceAPI}productFamily" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isChRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freePayPeriodFirstOn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freePayPeriodNextOn" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="switchOnPriority" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="chAddRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="firstPeriodRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="nextPeriodRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="freeRecipient" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="periodBlockCnt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="checkSubs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="periodBlockPrevCnt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="waitPeriodBlPrev" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}chargeBaseServ" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/schema/commonInVoiceAPI}countRecipient" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceInfo", propOrder = {
    "serviceName",
    "serviceId",
    "serviceTypeName",
    "serviceTypeId",
    "firstOn",
    "nextOn",
    "firstMonth",
    "nextMonth",
    "trplId",
    "serviceSettings",
    "param1",
    "trpkId",
    "acmId",
    "firstOnAdd",
    "nextOnAdd",
    "intDictId",
    "waitPeriodPayment",
    "notifyDay",
    "manageServ",
    "baseServId",
    "sgId",
    "bsgId",
    "isShared",
    "maxSharedSubs",
    "achmId",
    "isBasic",
    "productFamily",
    "sTypeName",
    "isChRecipient",
    "freePayPeriodFirstOn",
    "freePayPeriodNextOn",
    "switchOnPriority",
    "chAddRecipient",
    "firstPeriodRecipient",
    "nextPeriodRecipient",
    "freeRecipient",
    "periodBlockCnt",
    "checkSubs",
    "periodBlockPrevCnt",
    "waitPeriodBlPrev",
    "chargeBaseServ",
    "countRecipient"
})
public class ServiceInfo {

    protected String serviceName;
    protected BigDecimal serviceId;
    @XmlSchemaType(name = "string")
    protected ServiceTypeName serviceTypeName;
    protected BigDecimal serviceTypeId;
    protected BigDecimal firstOn;
    protected BigDecimal nextOn;
    protected BigDecimal firstMonth;
    protected BigDecimal nextMonth;
    protected BigDecimal trplId;
    protected List<ServiceSettingList> serviceSettings;
    protected BigDecimal param1;
    protected BigDecimal trpkId;
    protected BigDecimal acmId;
    protected BigDecimal firstOnAdd;
    protected BigDecimal nextOnAdd;
    protected BigDecimal intDictId;
    protected BigDecimal waitPeriodPayment;
    protected BigDecimal notifyDay;
    protected BigDecimal manageServ;
    protected BigDecimal baseServId;
    protected BigDecimal sgId;
    protected BigDecimal bsgId;
    protected BigDecimal isShared;
    protected BigDecimal maxSharedSubs;
    protected BigDecimal achmId;
    protected BigDecimal isBasic;
    protected List<ProductFamily> productFamily;
    protected String sTypeName;
    protected BigDecimal isChRecipient;
    protected BigDecimal freePayPeriodFirstOn;
    protected BigDecimal freePayPeriodNextOn;
    protected BigDecimal switchOnPriority;
    protected BigDecimal chAddRecipient;
    protected BigDecimal firstPeriodRecipient;
    protected BigDecimal nextPeriodRecipient;
    protected BigDecimal freeRecipient;
    protected BigDecimal periodBlockCnt;
    protected BigDecimal checkSubs;
    protected BigDecimal periodBlockPrevCnt;
    protected BigDecimal waitPeriodBlPrev;
    protected BigDecimal chargeBaseServ;
    protected BigDecimal countRecipient;

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceId(BigDecimal value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the serviceTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTypeName }
     *     
     */
    public ServiceTypeName getServiceTypeName() {
        return serviceTypeName;
    }

    /**
     * Sets the value of the serviceTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTypeName }
     *     
     */
    public void setServiceTypeName(ServiceTypeName value) {
        this.serviceTypeName = value;
    }

    /**
     * Gets the value of the serviceTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceTypeId() {
        return serviceTypeId;
    }

    /**
     * Sets the value of the serviceTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceTypeId(BigDecimal value) {
        this.serviceTypeId = value;
    }

    /**
     * Gets the value of the firstOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstOn() {
        return firstOn;
    }

    /**
     * Sets the value of the firstOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstOn(BigDecimal value) {
        this.firstOn = value;
    }

    /**
     * Gets the value of the nextOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextOn() {
        return nextOn;
    }

    /**
     * Sets the value of the nextOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextOn(BigDecimal value) {
        this.nextOn = value;
    }

    /**
     * Gets the value of the firstMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstMonth() {
        return firstMonth;
    }

    /**
     * Sets the value of the firstMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstMonth(BigDecimal value) {
        this.firstMonth = value;
    }

    /**
     * Gets the value of the nextMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextMonth() {
        return nextMonth;
    }

    /**
     * Sets the value of the nextMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextMonth(BigDecimal value) {
        this.nextMonth = value;
    }

    /**
     * Gets the value of the trplId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrplId() {
        return trplId;
    }

    /**
     * Sets the value of the trplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrplId(BigDecimal value) {
        this.trplId = value;
    }

    /**
     * Gets the value of the serviceSettings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceSettings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceSettings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceSettingList }
     * 
     * 
     */
    public List<ServiceSettingList> getServiceSettings() {
        if (serviceSettings == null) {
            serviceSettings = new ArrayList<ServiceSettingList>();
        }
        return this.serviceSettings;
    }

    /**
     * Gets the value of the param1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParam1() {
        return param1;
    }

    /**
     * Sets the value of the param1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParam1(BigDecimal value) {
        this.param1 = value;
    }

    /**
     * Gets the value of the trpkId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrpkId() {
        return trpkId;
    }

    /**
     * Sets the value of the trpkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrpkId(BigDecimal value) {
        this.trpkId = value;
    }

    /**
     * Gets the value of the acmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcmId() {
        return acmId;
    }

    /**
     * Sets the value of the acmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcmId(BigDecimal value) {
        this.acmId = value;
    }

    /**
     * Gets the value of the firstOnAdd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstOnAdd() {
        return firstOnAdd;
    }

    /**
     * Sets the value of the firstOnAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstOnAdd(BigDecimal value) {
        this.firstOnAdd = value;
    }

    /**
     * Gets the value of the nextOnAdd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextOnAdd() {
        return nextOnAdd;
    }

    /**
     * Sets the value of the nextOnAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextOnAdd(BigDecimal value) {
        this.nextOnAdd = value;
    }

    /**
     * Gets the value of the intDictId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIntDictId() {
        return intDictId;
    }

    /**
     * Sets the value of the intDictId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIntDictId(BigDecimal value) {
        this.intDictId = value;
    }

    /**
     * Gets the value of the waitPeriodPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaitPeriodPayment() {
        return waitPeriodPayment;
    }

    /**
     * Sets the value of the waitPeriodPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaitPeriodPayment(BigDecimal value) {
        this.waitPeriodPayment = value;
    }

    /**
     * Gets the value of the notifyDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNotifyDay() {
        return notifyDay;
    }

    /**
     * Sets the value of the notifyDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNotifyDay(BigDecimal value) {
        this.notifyDay = value;
    }

    /**
     * Gets the value of the manageServ property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getManageServ() {
        return manageServ;
    }

    /**
     * Sets the value of the manageServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setManageServ(BigDecimal value) {
        this.manageServ = value;
    }

    /**
     * Gets the value of the baseServId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseServId() {
        return baseServId;
    }

    /**
     * Sets the value of the baseServId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseServId(BigDecimal value) {
        this.baseServId = value;
    }

    /**
     * Gets the value of the sgId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSgId() {
        return sgId;
    }

    /**
     * Sets the value of the sgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSgId(BigDecimal value) {
        this.sgId = value;
    }

    /**
     * Gets the value of the bsgId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBsgId() {
        return bsgId;
    }

    /**
     * Sets the value of the bsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBsgId(BigDecimal value) {
        this.bsgId = value;
    }

    /**
     * Gets the value of the isShared property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsShared() {
        return isShared;
    }

    /**
     * Sets the value of the isShared property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsShared(BigDecimal value) {
        this.isShared = value;
    }

    /**
     * Gets the value of the maxSharedSubs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxSharedSubs() {
        return maxSharedSubs;
    }

    /**
     * Sets the value of the maxSharedSubs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxSharedSubs(BigDecimal value) {
        this.maxSharedSubs = value;
    }

    /**
     * Gets the value of the achmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAchmId() {
        return achmId;
    }

    /**
     * Sets the value of the achmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAchmId(BigDecimal value) {
        this.achmId = value;
    }

    /**
     * Gets the value of the isBasic property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsBasic() {
        return isBasic;
    }

    /**
     * Sets the value of the isBasic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsBasic(BigDecimal value) {
        this.isBasic = value;
    }

    /**
     * Gets the value of the productFamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productFamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductFamily }
     * 
     * 
     */
    public List<ProductFamily> getProductFamily() {
        if (productFamily == null) {
            productFamily = new ArrayList<ProductFamily>();
        }
        return this.productFamily;
    }

    /**
     * Gets the value of the sTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTypeName() {
        return sTypeName;
    }

    /**
     * Sets the value of the sTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTypeName(String value) {
        this.sTypeName = value;
    }

    /**
     * Gets the value of the isChRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsChRecipient() {
        return isChRecipient;
    }

    /**
     * Sets the value of the isChRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsChRecipient(BigDecimal value) {
        this.isChRecipient = value;
    }

    /**
     * Gets the value of the freePayPeriodFirstOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreePayPeriodFirstOn() {
        return freePayPeriodFirstOn;
    }

    /**
     * Sets the value of the freePayPeriodFirstOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreePayPeriodFirstOn(BigDecimal value) {
        this.freePayPeriodFirstOn = value;
    }

    /**
     * Gets the value of the freePayPeriodNextOn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreePayPeriodNextOn() {
        return freePayPeriodNextOn;
    }

    /**
     * Sets the value of the freePayPeriodNextOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreePayPeriodNextOn(BigDecimal value) {
        this.freePayPeriodNextOn = value;
    }

    /**
     * Gets the value of the switchOnPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSwitchOnPriority() {
        return switchOnPriority;
    }

    /**
     * Sets the value of the switchOnPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSwitchOnPriority(BigDecimal value) {
        this.switchOnPriority = value;
    }

    /**
     * Gets the value of the chAddRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChAddRecipient() {
        return chAddRecipient;
    }

    /**
     * Sets the value of the chAddRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChAddRecipient(BigDecimal value) {
        this.chAddRecipient = value;
    }

    /**
     * Gets the value of the firstPeriodRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstPeriodRecipient() {
        return firstPeriodRecipient;
    }

    /**
     * Sets the value of the firstPeriodRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstPeriodRecipient(BigDecimal value) {
        this.firstPeriodRecipient = value;
    }

    /**
     * Gets the value of the nextPeriodRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNextPeriodRecipient() {
        return nextPeriodRecipient;
    }

    /**
     * Sets the value of the nextPeriodRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNextPeriodRecipient(BigDecimal value) {
        this.nextPeriodRecipient = value;
    }

    /**
     * Gets the value of the freeRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreeRecipient() {
        return freeRecipient;
    }

    /**
     * Sets the value of the freeRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreeRecipient(BigDecimal value) {
        this.freeRecipient = value;
    }

    /**
     * Gets the value of the periodBlockCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodBlockCnt() {
        return periodBlockCnt;
    }

    /**
     * Sets the value of the periodBlockCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodBlockCnt(BigDecimal value) {
        this.periodBlockCnt = value;
    }

    /**
     * Gets the value of the checkSubs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCheckSubs() {
        return checkSubs;
    }

    /**
     * Sets the value of the checkSubs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCheckSubs(BigDecimal value) {
        this.checkSubs = value;
    }

    /**
     * Gets the value of the periodBlockPrevCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodBlockPrevCnt() {
        return periodBlockPrevCnt;
    }

    /**
     * Sets the value of the periodBlockPrevCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodBlockPrevCnt(BigDecimal value) {
        this.periodBlockPrevCnt = value;
    }

    /**
     * Gets the value of the waitPeriodBlPrev property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaitPeriodBlPrev() {
        return waitPeriodBlPrev;
    }

    /**
     * Sets the value of the waitPeriodBlPrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaitPeriodBlPrev(BigDecimal value) {
        this.waitPeriodBlPrev = value;
    }

    /**
     * Gets the value of the chargeBaseServ property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeBaseServ() {
        return chargeBaseServ;
    }

    /**
     * Sets the value of the chargeBaseServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeBaseServ(BigDecimal value) {
        this.chargeBaseServ = value;
    }

    /**
     * Gets the value of the countRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCountRecipient() {
        return countRecipient;
    }

    /**
     * Sets the value of the countRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCountRecipient(BigDecimal value) {
        this.countRecipient = value;
    }

}
