//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceStatusName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceStatusName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="active"/&gt;
 *     &lt;enumeration value="disabled"/&gt;
 *     &lt;enumeration value="blocked"/&gt;
 *     &lt;enumeration value="unlocked"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ServiceStatusName")
@XmlEnum
public enum ServiceStatusName {


    /**
     * Активный
     * 
     */
    @XmlEnumValue("active")
    ACTIVE("active"),

    /**
     * Отключенный
     * 
     */
    @XmlEnumValue("disabled")
    DISABLED("disabled"),

    /**
     * Заблокированный
     * 
     */
    @XmlEnumValue("blocked")
    BLOCKED("blocked"),

    /**
     * Разблокированный
     * 
     */
    @XmlEnumValue("unlocked")
    UNLOCKED("unlocked");
    private final String value;

    ServiceStatusName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceStatusName fromValue(String v) {
        for (ServiceStatusName c: ServiceStatusName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
