//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTypeName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceTypeName"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="periodic_traffic"/&gt;
 *     &lt;enumeration value="periodic"/&gt;
 *     &lt;enumeration value="single"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ServiceTypeName")
@XmlEnum
public enum ServiceTypeName {


    /**
     * Периодическая с трафиком
     * 
     */
    @XmlEnumValue("periodic_traffic")
    PERIODIC_TRAFFIC("periodic_traffic"),

    /**
     * Периодческая
     * 
     */
    @XmlEnumValue("periodic")
    PERIODIC("periodic"),

    /**
     * Одинарная
     * 
     */
    @XmlEnumValue("single")
    SINGLE("single");
    private final String value;

    ServiceTypeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceTypeName fromValue(String v) {
        for (ServiceTypeName c: ServiceTypeName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
