//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Параметры услуги абонента
 * 
 * <p>Java class for ServiceParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subs_id" type="{http://www.bercut.com/schema/commonInVoiceAPI}subscriberId"/&gt;
 *         &lt;element name="serv_id" type="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId"/&gt;
 *         &lt;element name="num_history" type="{http://www.bercut.com/schema/commonInVoiceAPI}numberHistory"/&gt;
 *         &lt;element name="stime" type="{http://www.bercut.com/schema/commonInVoiceAPI}sDate"/&gt;
 *         &lt;element name="etime" type="{http://www.bercut.com/schema/commonInVoiceAPI}eDate"/&gt;
 *         &lt;element name="param_num" type="{http://www.bercut.com/schema/commonInVoiceAPI}paramNum"/&gt;
 *         &lt;element name="param_value" type="{http://www.bercut.com/schema/commonInVoiceAPI}paramValue"/&gt;
 *         &lt;element name="is_changeable" type="{http://www.bercut.com/schema/commonInVoiceAPI}isChangeable"/&gt;
 *         &lt;element name="spft_id" type="{http://www.bercut.com/schema/commonInVoiceAPI}spftId"/&gt;
 *         &lt;element name="sp_group_id" type="{http://www.bercut.com/schema/commonInVoiceAPI}spGroupId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceParameters", propOrder = {
    "subsId",
    "servId",
    "numHistory",
    "stime",
    "etime",
    "paramNum",
    "paramValue",
    "isChangeable",
    "spftId",
    "spGroupId"
})
public class ServiceParameters {

    @XmlElement(name = "subs_id", required = true)
    protected BigDecimal subsId;
    @XmlElement(name = "serv_id", required = true)
    protected BigDecimal servId;
    @XmlElement(name = "num_history", required = true)
    protected BigDecimal numHistory;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar stime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar etime;
    @XmlElement(name = "param_num", required = true)
    protected BigDecimal paramNum;
    @XmlElement(name = "param_value", required = true)
    protected String paramValue;
    @XmlElement(name = "is_changeable", required = true)
    protected BigDecimal isChangeable;
    @XmlElement(name = "spft_id", required = true)
    protected BigDecimal spftId;
    @XmlElement(name = "sp_group_id", required = true)
    protected BigDecimal spGroupId;

    /**
     * Gets the value of the subsId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubsId() {
        return subsId;
    }

    /**
     * Sets the value of the subsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubsId(BigDecimal value) {
        this.subsId = value;
    }

    /**
     * Gets the value of the servId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServId() {
        return servId;
    }

    /**
     * Sets the value of the servId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServId(BigDecimal value) {
        this.servId = value;
    }

    /**
     * Gets the value of the numHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumHistory() {
        return numHistory;
    }

    /**
     * Sets the value of the numHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumHistory(BigDecimal value) {
        this.numHistory = value;
    }

    /**
     * Gets the value of the stime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStime() {
        return stime;
    }

    /**
     * Sets the value of the stime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStime(XMLGregorianCalendar value) {
        this.stime = value;
    }

    /**
     * Gets the value of the etime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEtime() {
        return etime;
    }

    /**
     * Sets the value of the etime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEtime(XMLGregorianCalendar value) {
        this.etime = value;
    }

    /**
     * Gets the value of the paramNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParamNum() {
        return paramNum;
    }

    /**
     * Sets the value of the paramNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParamNum(BigDecimal value) {
        this.paramNum = value;
    }

    /**
     * Gets the value of the paramValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * Sets the value of the paramValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamValue(String value) {
        this.paramValue = value;
    }

    /**
     * Gets the value of the isChangeable property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIsChangeable() {
        return isChangeable;
    }

    /**
     * Sets the value of the isChangeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIsChangeable(BigDecimal value) {
        this.isChangeable = value;
    }

    /**
     * Gets the value of the spftId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpftId() {
        return spftId;
    }

    /**
     * Sets the value of the spftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpftId(BigDecimal value) {
        this.spftId = value;
    }

    /**
     * Gets the value of the spGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpGroupId() {
        return spGroupId;
    }

    /**
     * Sets the value of the spGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpGroupId(BigDecimal value) {
        this.spGroupId = value;
    }

}
