//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Исторический набор параметров информации по трафику
 * 
 * <p>Java class for TrafikHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafikHistory"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serviceId" type="{http://www.bercut.com/schema/commonInVoiceAPI}serviceId" minOccurs="0"/&gt;
 *         &lt;element name="caltId" type="{http://www.bercut.com/schema/commonInVoiceAPI}caltId" minOccurs="0"/&gt;
 *         &lt;element name="tclsId" type="{http://www.bercut.com/schema/commonInVoiceAPI}tclsId" minOccurs="0"/&gt;
 *         &lt;element name="numberHistory" type="{http://www.bercut.com/schema/commonInVoiceAPI}numberHistory" minOccurs="0"/&gt;
 *         &lt;element name="stime" type="{http://www.bercut.com/schema/commonInVoiceAPI}sDate" minOccurs="0"/&gt;
 *         &lt;element name="eTime" type="{http://www.bercut.com/schema/commonInVoiceAPI}eDate" minOccurs="0"/&gt;
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="connectionPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="dcdmId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="priceOut" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="smstId" type="{http://www.bercut.com/schema/commonInVoiceAPI}smstId" minOccurs="0"/&gt;
 *         &lt;element name="areaId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="maxDur1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="maxDur2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafikHistory", propOrder = {
    "serviceId",
    "caltId",
    "tclsId",
    "numberHistory",
    "stime",
    "eTime",
    "price",
    "connectionPrice",
    "dcdmId",
    "priceOut",
    "smstId",
    "areaId",
    "maxDur1",
    "maxDur2"
})
public class TrafikHistory {

    protected BigDecimal serviceId;
    protected BigDecimal caltId;
    protected BigDecimal tclsId;
    protected BigDecimal numberHistory;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar stime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eTime;
    protected BigDecimal price;
    protected BigDecimal connectionPrice;
    protected BigDecimal dcdmId;
    protected BigDecimal priceOut;
    protected BigDecimal smstId;
    protected BigDecimal areaId;
    protected BigDecimal maxDur1;
    protected BigDecimal maxDur2;

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServiceId(BigDecimal value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the caltId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCaltId() {
        return caltId;
    }

    /**
     * Sets the value of the caltId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCaltId(BigDecimal value) {
        this.caltId = value;
    }

    /**
     * Gets the value of the tclsId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTclsId() {
        return tclsId;
    }

    /**
     * Sets the value of the tclsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTclsId(BigDecimal value) {
        this.tclsId = value;
    }

    /**
     * Gets the value of the numberHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumberHistory() {
        return numberHistory;
    }

    /**
     * Sets the value of the numberHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumberHistory(BigDecimal value) {
        this.numberHistory = value;
    }

    /**
     * Gets the value of the stime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStime() {
        return stime;
    }

    /**
     * Sets the value of the stime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStime(XMLGregorianCalendar value) {
        this.stime = value;
    }

    /**
     * Gets the value of the eTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETime() {
        return eTime;
    }

    /**
     * Sets the value of the eTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETime(XMLGregorianCalendar value) {
        this.eTime = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the connectionPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConnectionPrice() {
        return connectionPrice;
    }

    /**
     * Sets the value of the connectionPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConnectionPrice(BigDecimal value) {
        this.connectionPrice = value;
    }

    /**
     * Gets the value of the dcdmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDcdmId() {
        return dcdmId;
    }

    /**
     * Sets the value of the dcdmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDcdmId(BigDecimal value) {
        this.dcdmId = value;
    }

    /**
     * Gets the value of the priceOut property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceOut() {
        return priceOut;
    }

    /**
     * Sets the value of the priceOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceOut(BigDecimal value) {
        this.priceOut = value;
    }

    /**
     * Gets the value of the smstId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSmstId() {
        return smstId;
    }

    /**
     * Sets the value of the smstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSmstId(BigDecimal value) {
        this.smstId = value;
    }

    /**
     * Gets the value of the areaId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAreaId(BigDecimal value) {
        this.areaId = value;
    }

    /**
     * Gets the value of the maxDur1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxDur1() {
        return maxDur1;
    }

    /**
     * Sets the value of the maxDur1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxDur1(BigDecimal value) {
        this.maxDur1 = value;
    }

    /**
     * Gets the value of the maxDur2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxDur2() {
        return maxDur2;
    }

    /**
     * Sets the value of the maxDur2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxDur2(BigDecimal value) {
        this.maxDur2 = value;
    }

}
