//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 05:02:25 PM MSK 
//


package com.bercut.service.rates_management;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Не используется в SA
 * 
 * <p>Java class for updateSubscriberRateRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateSubscriberRateRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="branchId" type="{http://www.bercut.com/schema/commonInVoiceAPI}BranchId"/&gt;
 *         &lt;element name="contractName" type="{http://www.bercut.com/cc/sa/ratesmanagement}updateSubscriberRateContractName"/&gt;
 *         &lt;element name="subscriber" type="{http://www.bercut.com/schema/commonInVoiceAPI}subscriber"/&gt;
 *         &lt;element name="trplId" type="{http://www.bercut.com/cc/sa/ratesmanagement}trplId"/&gt;
 *         &lt;element name="tarServiceSyncFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="talId" type="{http://www.bercut.com/cc/sa/ratesmanagement}talId" minOccurs="0"/&gt;
 *         &lt;element name="taId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="tssId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="oneTimeTssId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="extendedRule" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="reId" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="chargeTrpl" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="baseServChargeOrder" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="checkSwitchon" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateSubscriberRateRequest", namespace = "http://www.bercut.com/cc/sa/ratesmanagement", propOrder = {
    "branchId",
    "contractName",
    "subscriber",
    "trplId",
    "tarServiceSyncFlag",
    "talId",
    "taId",
    "tssId",
    "oneTimeTssId",
    "extendedRule",
    "reId",
    "chargeTrpl",
    "baseServChargeOrder",
    "checkSwitchon"
})
public class UpdateSubscriberRateRequest {

    @XmlElement(namespace = "", required = true)
    protected BigDecimal branchId;
    @XmlElement(namespace = "", required = true)
    protected String contractName;
    @XmlElement(namespace = "", required = true)
    protected Subscriber subscriber;
    @XmlElement(namespace = "", required = true)
    protected BigDecimal trplId;
    @XmlElement(namespace = "")
    protected boolean tarServiceSyncFlag;
    @XmlElement(namespace = "")
    protected BigDecimal talId;
    @XmlElement(namespace = "")
    protected BigDecimal taId;
    @XmlElement(namespace = "")
    protected BigDecimal tssId;
    @XmlElement(namespace = "")
    protected BigDecimal oneTimeTssId;
    @XmlElement(namespace = "")
    protected BigDecimal extendedRule;
    @XmlElement(namespace = "")
    protected BigDecimal reId;
    @XmlElement(namespace = "")
    protected BigDecimal chargeTrpl;
    @XmlElement(namespace = "")
    protected BigDecimal baseServChargeOrder;
    @XmlElement(namespace = "")
    protected BigDecimal checkSwitchon;

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBranchId(BigDecimal value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the contractName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * Sets the value of the contractName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractName(String value) {
        this.contractName = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link Subscriber }
     *     
     */
    public Subscriber getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subscriber }
     *     
     */
    public void setSubscriber(Subscriber value) {
        this.subscriber = value;
    }

    /**
     * Gets the value of the trplId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrplId() {
        return trplId;
    }

    /**
     * Sets the value of the trplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrplId(BigDecimal value) {
        this.trplId = value;
    }

    /**
     * Gets the value of the tarServiceSyncFlag property.
     * 
     */
    public boolean isTarServiceSyncFlag() {
        return tarServiceSyncFlag;
    }

    /**
     * Sets the value of the tarServiceSyncFlag property.
     * 
     */
    public void setTarServiceSyncFlag(boolean value) {
        this.tarServiceSyncFlag = value;
    }

    /**
     * Gets the value of the talId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTalId() {
        return talId;
    }

    /**
     * Sets the value of the talId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTalId(BigDecimal value) {
        this.talId = value;
    }

    /**
     * Gets the value of the taId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaId() {
        return taId;
    }

    /**
     * Sets the value of the taId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaId(BigDecimal value) {
        this.taId = value;
    }

    /**
     * Gets the value of the tssId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTssId() {
        return tssId;
    }

    /**
     * Sets the value of the tssId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTssId(BigDecimal value) {
        this.tssId = value;
    }

    /**
     * Gets the value of the oneTimeTssId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOneTimeTssId() {
        return oneTimeTssId;
    }

    /**
     * Sets the value of the oneTimeTssId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOneTimeTssId(BigDecimal value) {
        this.oneTimeTssId = value;
    }

    /**
     * Gets the value of the extendedRule property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtendedRule() {
        return extendedRule;
    }

    /**
     * Sets the value of the extendedRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtendedRule(BigDecimal value) {
        this.extendedRule = value;
    }

    /**
     * Gets the value of the reId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReId() {
        return reId;
    }

    /**
     * Sets the value of the reId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReId(BigDecimal value) {
        this.reId = value;
    }

    /**
     * Gets the value of the chargeTrpl property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeTrpl() {
        return chargeTrpl;
    }

    /**
     * Sets the value of the chargeTrpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeTrpl(BigDecimal value) {
        this.chargeTrpl = value;
    }

    /**
     * Gets the value of the baseServChargeOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseServChargeOrder() {
        return baseServChargeOrder;
    }

    /**
     * Sets the value of the baseServChargeOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseServChargeOrder(BigDecimal value) {
        this.baseServChargeOrder = value;
    }

    /**
     * Gets the value of the checkSwitchon property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCheckSwitchon() {
        return checkSwitchon;
    }

    /**
     * Sets the value of the checkSwitchon property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCheckSwitchon(BigDecimal value) {
        this.checkSwitchon = value;
    }

}
