//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 06:01:22 PM MSK 
//


package com.bercut.service.wsdl.service_profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Services description array request. Response on this request contains only service description without any parameters and messages and macros specific with multi criteria
 * 
 * <p>Java class for FindMultiCriteriaServicesRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindMultiCriteriaServicesRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/schema/SimpleDefinition}branchId"/&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/schema/ComplexDefinition}serviceIds" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/dsi/ServiceProfile}serviceCriteria" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/dsi/ServiceProfile}multiConcreteServiceCriteria" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/dsi/ServiceProfile}timeTag" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/schema/ComplexDefinition}pagination" minOccurs="0"/&gt;
 *         &lt;element name="extension" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="useContains" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="extension" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindMultiCriteriaServicesRequest", propOrder = {
    "branchId",
    "serviceIds",
    "serviceCriteria",
    "multiConcreteServiceCriteria",
    "timeTag",
    "pagination",
    "extension"
})
public class FindMultiCriteriaServicesRequest {

    @XmlElement(namespace = "http://www.bercut.com/spec/schema/SimpleDefinition")
    @XmlSchemaType(name = "unsignedInt")
    protected long branchId;
    @XmlElement(namespace = "http://www.bercut.com/spec/schema/ComplexDefinition")
    protected ServiceIds serviceIds;
    protected ServiceCriteria serviceCriteria;
    protected MultiConcreteServiceCriteria multiConcreteServiceCriteria;
    protected TimeAndTagCriteria timeTag;
    @XmlElement(namespace = "http://www.bercut.com/spec/schema/ComplexDefinition")
    protected Pagination pagination;
    protected FindMultiCriteriaServicesRequest.Extension extension;

    /**
     * Gets the value of the branchId property.
     * 
     */
    public long getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     */
    public void setBranchId(long value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the serviceIds property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceIds }
     *     
     */
    public ServiceIds getServiceIds() {
        return serviceIds;
    }

    /**
     * Sets the value of the serviceIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceIds }
     *     
     */
    public void setServiceIds(ServiceIds value) {
        this.serviceIds = value;
    }

    /**
     * Gets the value of the serviceCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCriteria }
     *     
     */
    public ServiceCriteria getServiceCriteria() {
        return serviceCriteria;
    }

    /**
     * Sets the value of the serviceCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCriteria }
     *     
     */
    public void setServiceCriteria(ServiceCriteria value) {
        this.serviceCriteria = value;
    }

    /**
     * Gets the value of the multiConcreteServiceCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link MultiConcreteServiceCriteria }
     *     
     */
    public MultiConcreteServiceCriteria getMultiConcreteServiceCriteria() {
        return multiConcreteServiceCriteria;
    }

    /**
     * Sets the value of the multiConcreteServiceCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiConcreteServiceCriteria }
     *     
     */
    public void setMultiConcreteServiceCriteria(MultiConcreteServiceCriteria value) {
        this.multiConcreteServiceCriteria = value;
    }

    /**
     * Gets the value of the timeTag property.
     * 
     * @return
     *     possible object is
     *     {@link TimeAndTagCriteria }
     *     
     */
    public TimeAndTagCriteria getTimeTag() {
        return timeTag;
    }

    /**
     * Sets the value of the timeTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeAndTagCriteria }
     *     
     */
    public void setTimeTag(TimeAndTagCriteria value) {
        this.timeTag = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link FindMultiCriteriaServicesRequest.Extension }
     *     
     */
    public FindMultiCriteriaServicesRequest.Extension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link FindMultiCriteriaServicesRequest.Extension }
     *     
     */
    public void setExtension(FindMultiCriteriaServicesRequest.Extension value) {
        this.extension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="useContains" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="extension" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "useContains",
        "extension"
    })
    public static class Extension {

        protected Boolean useContains;
        protected Extension extension;

        /**
         * Gets the value of the useContains property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUseContains() {
            return useContains;
        }

        /**
         * Sets the value of the useContains property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUseContains(Boolean value) {
            this.useContains = value;
        }

        /**
         * Gets the value of the extension property.
         * 
         * @return
         *     possible object is
         *     {@link Extension }
         *     
         */
        public Extension getExtension() {
            return extension;
        }

        /**
         * Sets the value of the extension property.
         * 
         * @param value
         *     allowed object is
         *     {@link Extension }
         *     
         */
        public void setExtension(Extension value) {
            this.extension = value;
        }
    }

}
