//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 06:01:22 PM MSK 
//


package com.bercut.service.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrencyCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CurrencyCode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RUB"/&gt;
 *     &lt;enumeration value="AUD"/&gt;
 *     &lt;enumeration value="AZN"/&gt;
 *     &lt;enumeration value="GBP"/&gt;
 *     &lt;enumeration value="AMD"/&gt;
 *     &lt;enumeration value="BYR"/&gt;
 *     &lt;enumeration value="BGN"/&gt;
 *     &lt;enumeration value="BRL"/&gt;
 *     &lt;enumeration value="HUF"/&gt;
 *     &lt;enumeration value="DKK"/&gt;
 *     &lt;enumeration value="USD"/&gt;
 *     &lt;enumeration value="EUR"/&gt;
 *     &lt;enumeration value="INR"/&gt;
 *     &lt;enumeration value="KZT"/&gt;
 *     &lt;enumeration value="CAD"/&gt;
 *     &lt;enumeration value="KGS"/&gt;
 *     &lt;enumeration value="CNY"/&gt;
 *     &lt;enumeration value="LTL"/&gt;
 *     &lt;enumeration value="MDL"/&gt;
 *     &lt;enumeration value="NOK"/&gt;
 *     &lt;enumeration value="PLN"/&gt;
 *     &lt;enumeration value="RON"/&gt;
 *     &lt;enumeration value="XDR"/&gt;
 *     &lt;enumeration value="SGD"/&gt;
 *     &lt;enumeration value="TJS"/&gt;
 *     &lt;enumeration value="TRY"/&gt;
 *     &lt;enumeration value="TMT"/&gt;
 *     &lt;enumeration value="UZS"/&gt;
 *     &lt;enumeration value="UAH"/&gt;
 *     &lt;enumeration value="CZK"/&gt;
 *     &lt;enumeration value="SEK"/&gt;
 *     &lt;enumeration value="CHF"/&gt;
 *     &lt;enumeration value="ZAR"/&gt;
 *     &lt;enumeration value="KRW"/&gt;
 *     &lt;enumeration value="JPY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CurrencyCode", namespace = "http://www.bercut.com/spec/schema/SimpleDefinition")
@XmlEnum
public enum CurrencyCode {


    /**
     * Russian ruble
     * 
     */
    RUB,

    /**
     * Australian Dollar
     * 
     */
    AUD,

    /**
     * Azerbaijan Manat
     * 
     */
    AZN,

    /**
     * British Pound Sterling
     * 
     */
    GBP,

    /**
     * Armenia Dram
     * 
     */
    AMD,

    /**
     * Belarussian Ruble
     * 
     */
    BYR,

    /**
     * Bulgarian lev
     * 
     */
    BGN,

    /**
     * Brazil Real
     * 
     */
    BRL,

    /**
     * Hungarian Forint
     * 
     */
    HUF,

    /**
     * Danish Krone
     * 
     */
    DKK,

    /**
     * US Dollar
     * 
     */
    USD,

    /**
     * Euro
     * 
     */
    EUR,

    /**
     * Indian Rupee
     * 
     */
    INR,

    /**
     * Kazakh Tenge
     * 
     */
    KZT,

    /**
     * Canadian Dollar
     * 
     */
    CAD,

    /**
     * Kyrgyzstan Som
     * 
     */
    KGS,

    /**
     * China Yuan
     * 
     */
    CNY,

    /**
     * Lithuanian Lita
     * 
     */
    LTL,

    /**
     * Moldova Lei
     * 
     */
    MDL,

    /**
     * Norwegian Krone
     * 
     */
    NOK,

    /**
     * Polish Zloty
     * 
     */
    PLN,

    /**
     * Romanian Leu
     * 
     */
    RON,

    /**
     * SDR
     * 
     */
    XDR,

    /**
     * Singapore Dollar
     * 
     */
    SGD,

    /**
     * Tajikistan Ruble
     * 
     */
    TJS,

    /**
     * Turkish Lira
     * 
     */
    TRY,

    /**
     * New Turkmenistan Manat
     * 
     */
    TMT,

    /**
     * Uzbekistan Sum
     * 
     */
    UZS,

    /**
     * Ukrainian Hryvnia
     * 
     */
    UAH,

    /**
     * Czech Koruna
     * 
     */
    CZK,

    /**
     * Swedish Krona
     * 
     */
    SEK,

    /**
     * Swiss Franc
     * 
     */
    CHF,

    /**
     * S.African Rand
     * 
     */
    ZAR,

    /**
     * South Korean Won
     * 
     */
    KRW,

    /**
     * Japanese Yen
     * 
     */
    JPY;

    public String value() {
        return name();
    }

    public static CurrencyCode fromValue(String v) {
        return valueOf(v);
    }

}
