//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 06:01:22 PM MSK 
//


package com.bercut.service.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Service description/data request. Service description or data request depends on contact value
 * 
 * <p>Java class for MultiXPathReadServiceRequestParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiXPathReadServiceRequestParams"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.bercut.com/spec/dsi/ServiceProfile}multiXPathReadServicesRequest" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiXPathReadServiceRequestParams", propOrder = {
    "multiXPathReadServicesRequest"
})
public class MultiXPathReadServiceRequestParams {

    @XmlElement(required = true)
    protected List<MultiXPathReadServicesRequest> multiXPathReadServicesRequest;

    /**
     * Gets the value of the multiXPathReadServicesRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiXPathReadServicesRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiXPathReadServicesRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiXPathReadServicesRequest }
     * 
     * 
     */
    public List<MultiXPathReadServicesRequest> getMultiXPathReadServicesRequest() {
        if (multiXPathReadServicesRequest == null) {
            multiXPathReadServicesRequest = new ArrayList<MultiXPathReadServicesRequest>();
        }
        return this.multiXPathReadServicesRequest;
    }

}
