//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 06:01:22 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bercut.com/spec/dsi/ServiceProfile", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bercut.service.wsdl;
