//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.27 at 06:01:22 PM MSK 
//


package com.bercut.service.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="active"/&gt;
 *     &lt;enumeration value="unactive"/&gt;
 *     &lt;enumeration value="blocked"/&gt;
 *     &lt;enumeration value="unblocked"/&gt;
 *     &lt;enumeration value="testing"/&gt;
 *     &lt;enumeration value="archived"/&gt;
 *     &lt;enumeration value="canceled"/&gt;
 *     &lt;enumeration value="expired"/&gt;
 *     &lt;enumeration value="__unknown__"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ServiceStatus", namespace = "http://www.bercut.com/spec/schema/SimpleDefinition")
@XmlEnum
public enum ServiceStatus {


    /**
     * Аctive service
     * 
     */
    @XmlEnumValue("active")
    ACTIVE("active"),

    /**
     * Non active service
     * 
     */
    @XmlEnumValue("unactive")
    UNACTIVE("unactive"),

    /**
     * Service blocked
     * 
     */
    @XmlEnumValue("blocked")
    BLOCKED("blocked"),

    /**
     * Service unblocked
     * 
     */
    @XmlEnumValue("unblocked")
    UNBLOCKED("unblocked"),

    /**
     * Service testing
     * 
     */
    @XmlEnumValue("testing")
    TESTING("testing"),

    /**
     * Service archived
     * 
     */
    @XmlEnumValue("archived")
    ARCHIVED("archived"),

    /**
     * Service canceled
     * 
     */
    @XmlEnumValue("canceled")
    CANCELED("canceled"),

    /**
     * Service expired
     * 
     */
    @XmlEnumValue("expired")
    EXPIRED("expired"),

    /**
     * unknown value (for the possibility of extending the set without losing compatibility)
     * 
     */
    @XmlEnumValue("__unknown__")
    UNKNOWN("__unknown__");
    private final String value;

    ServiceStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceStatus fromValue(String v) {
        for (ServiceStatus c: ServiceStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
